--- 
abstract: Catch the keyword from a search that brought a visitor to your CatApp.
author: Ashley Pond V  C<< <ashley@cpan.org> >>.
build_requires: 
  Catalyst::Runtime: 5.7
  Class::Accessor::Fast: 0
  Test::More: 0.42
  URI: 0
  URI::QueryParam: 0
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Catalyst-Plugin-ReferingKeyword
no_index: 
  directory: 
    - inc
    - t
version: 0.01
